---
- hosts: linuxSlave
  tasks:
    - name: Copy script to andere node
      copy:
        src: /home/ansible/script.sh
        dest: /home/ansible/script.sh
        owner: ansible
        group: ansible
        mode: 0744
    - name: Execute script remote
      shell: /home/ansible/script.sh > /home/ansible/output.txt
