---
- hosts: windows
  tasks:
  - name: Warn logged in users of impending upgrade
    win_toast: 
      expire: 60
      title: System Upgrade Notification
      msg: Automated upgrade about to start. Please save your work and log off before 14:00
    async: 60
    poll: 0
